fix: postgres exception occurred while fetching the conversation list. (#327)
* fix: postgres exception occurred while fetching the conversation list.
ERROR:  SELECT DISTINCT ON expressions must match initial ORDER BY expressions

* fix: apply fixes from styleci

* fix: type "Message" entity instead of "void"